### ISSUE TITLE
Look into replacing hard-coded domain ^^^

### ISSUE THREAD

**Issue by danjoneslf** [alphagov/cyber-security-windows-sandbox#5]
This is currently hard-coded in a lot of places. 

- [x] Replace in TF for DC and WEC
- [x] Replace in provisioning powershell scripts 
- [x] Replace in XML for GPOs
- [x] Replace in XML for WEF subscriptions
- [x] Test it's working...

**Comment by alice-carr** [comment]
Didn't get as far with this as I wanted to today:

-  I added the domain as a variable in TF and removed the hard coding in the terraform files.
-  I looked into how we could do this in the powershell files but I haven't come to any conclusions just yet - I'm still working powershell out and I can see a bunch of .ps1 files that include the domain name, but I can't quite figure out how these files are called / used. We can pass arguments in when calling powershell functions from the command line though.

**Comment by danjoneslf** [comment]
There are also a bunch of references in XML files for the forwarder subscriptions and global policy objects. I think probably given the only way to replace those ones is (I think) to template them and populate the domain into a placeholder variable, it's probably easiest to do that for everything. So just iterate over everything in scripts and pass it through something like jinja to move it from a templates location to the scripts location and populate the placeholders. 

In terms of how they're used the ec2 terraforms for the DC and WEC instance each have a remote-exec which clones the repo and runs the scripts so I guess the domain would be passed into the remote-exec script as an env var maybe and then we'd have to replace the content of that script with a wrapper script that dealt with the domain and then ran the same tasks.

**Comment by danjoneslf** [comment]
Given it's just a string replace and we're in PS land it might be better to just do this: https://mcpmag.com/articles/2018/08/08/replace-text-with-powershell.aspx so we don't have to install a python runtime and requirements and whatnot.

**Comment by danjoneslf** [comment]
Then you could just use Set-Content to overwrite the files in-place.
